/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description pmdf-storeのルートディレクトリへアクセス可能かを簡易チェックする。
     */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations["refresh_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create User */
    post: operations["create_user_admin_users_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users/{user_id}/scopes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Scopes */
    put: operations["update_scopes_admin_users__user_id__scopes_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/audit/records": {
    parameters: {
      query?: {
        actor?: string | null;
        action?: string | null;
        kind?: string | null;
        date_from?: string | null;
        date_to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Records
     * @description 監査ログをフィルタ条件で絞り込み、新しい順に返す。
     */
    get: operations["list_records_audit_records_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/approvals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Proposals */
    get: operations["list_proposals_approvals_get"];
    put?: never;
    /** Propose */
    post: operations["propose_approvals_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/approvals/{proposal_id}/decide": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Decide */
    post: operations["decide_approvals__proposal_id__decide_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/autonomy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Autonomy Levels */
    get: operations["get_autonomy_levels_autonomy_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/autonomy/{product_id}/{business_function}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set Autonomy Level */
    put: operations["set_autonomy_level_autonomy__product_id___business_function__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/autonomy/emergency-stop/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Emergency Stop Status
     * @description 緊急停止状態の照会(E5-1: agent-coreが毎ステップ照会する読み取り専用API)。
     *
     *     トリガー・解除(admin専用)とは異なり、認証済みであればロールを
     *     問わず参照できる(agent-coreのサービスアカウントがeditor/admin
     *     いずれであっても照会できるようにするため)。
     */
    get: operations["get_emergency_stop_status_autonomy_emergency_stop_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/autonomy/emergency-stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger Emergency Stop */
    post: operations["trigger_emergency_stop_autonomy_emergency_stop_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/autonomy/emergency-stop/release": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Release Emergency Stop */
    post: operations["release_emergency_stop_autonomy_emergency_stop_release_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bundles/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Export Entities
     * @description スコープに合致するエンティティを`*.pmdf.tar.gz`としてエクスポートする。
     */
    post: operations["export_entities_bundles_export_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bundles/import/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Validate
     * @description バンドルのスキーマ検証+差分プレビューを行う(この時点では未適用)。
     */
    post: operations["import_validate_bundles_import_validate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/bundles/import/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Apply
     * @description バンドルを検証のうえストアへ適用する(1コミット、監査ログに1エントリ記録)。
     */
    post: operations["import_apply_bundles_import_apply_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chat/instructions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Post Instructions
     * @description 自然文の指示を受け付け、`pending`状態のチャットタスクとして登録する。
     */
    post: operations["post_instructions_chat_instructions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chat/tasks": {
    parameters: {
      query?: {
        status?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tasks
     * @description チャットタスク一覧を新しい順に返す(E7-6のエージェント活動ログ画面向け)。
     */
    get: operations["list_tasks_chat_tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chat/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Task
     * @description チャットタスクの現在の実行状況を返す。
     */
    get: operations["get_task_chat_tasks__task_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/chat/tasks/{task_id}/transition": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Transition Task
     * @description agent-coreランナーからのタスク状態遷移報告を受け付ける(受理/実行中/完了/失敗)。
     *
     *     `running`/`done`/`failed`への遷移のみを許可し(`pending`は
     *     `post_instructions`でのみ設定される)、不正な遷移は409を返す。
     */
    post: operations["transition_task_chat_tasks__task_id__transition_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/costs/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record Usage
     * @description LLM呼び出し1件分のusageを記録する(admin/editorのみ、AR-04)。
     */
    post: operations["record_usage_costs_usage_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/costs/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Cost Summary
     * @description 月次予算に対する消化率と、モデル別・論理名別・日別の集計を返す(閲覧はviewer以上)。
     */
    get: operations["get_cost_summary_costs_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pmdf/decision/{id}/execute": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Execute Decision
     * @description decisionの実行(L1)。承認ゲート通過後、対象decisionを返す(実行内容自体はE5で拡張)。
     */
    post: operations["execute_decision_pmdf_decision__id__execute_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/roadmap/{id}/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm Roadmap Item
     * @description roadmap_itemの確定(L1)。承認ゲート通過後、対象roadmap_itemを返す。
     */
    post: operations["confirm_roadmap_item_roadmap__id__confirm_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/release/{id}/go-no-go": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Release Go No Go
     * @description releaseのgo/no-go判定実行(L1)。承認ゲート通過後、対象releaseを返す。
     */
    post: operations["release_go_no_go_release__id__go_no_go_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/stakeholder/{id}/send-message": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Send Stakeholder Message
     * @description ステークホルダーへのメッセージ送信実行(L1、E5-7)。承認ゲート通過後、対象stakeholderを返す。
     *
     *     文案生成(draft)自体はL2で承認不要だが、実際の送信(外部送信相当の
     *     アクション)はL1として本エンドポイント経由でのみ実行可能とする。
     */
    post: operations["send_stakeholder_message_stakeholder__id__send_message_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pmdf/{kind}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Entities */
    get: operations["list_entities_pmdf__kind__get"];
    put?: never;
    /** Create Entity */
    post: operations["create_entity_pmdf__kind__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pmdf/{kind}/{id}/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Entity History */
    get: operations["get_entity_history_pmdf__kind___id__history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pmdf/{kind}/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Entity */
    get: operations["get_entity_pmdf__kind___id__get"];
    /** Update Entity */
    put: operations["update_entity_pmdf__kind___id__put"];
    post?: never;
    /**
     * Delete Entity
     * @description DR-06: approval/decisionは削除不可。それ以外も物理削除APIは提供しない。
     */
    delete: operations["delete_entity_pmdf__kind___id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AggregatedUsageResponseEntry */
    AggregatedUsageResponseEntry: {
      /** Key */
      key: string;
      /** Call Count */
      call_count: number;
      /** Total Tokens */
      total_tokens: number;
      /** Total Cost Jpy */
      total_cost_jpy: number;
      /** Total Latency Ms */
      total_latency_ms: number;
    };
    /**
     * AuditRecord
     * @description 監査ログ1レコード分の情報。
     */
    AuditRecord: {
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /** Actor */
      actor: string;
      /** Action */
      action: string;
      /** Target Kind */
      target_kind: string;
      /** Target Id */
      target_id: string;
      /** Detail */
      detail?: {
        [key: string]: unknown;
      };
      /** Prev Hash */
      prev_hash?: string | null;
      /** Hash */
      hash: string;
    };
    /**
     * AutonomyConfig
     * @description 1つの(product_id, business_function)組に対する自律レベル設定。
     */
    AutonomyConfig: {
      /** Product Id */
      product_id: string;
      /**
       * Business Function
       * @enum {string}
       */
      business_function:
        | "vision"
        | "roadmap"
        | "discovery"
        | "backlog"
        | "kpi_monitoring"
        | "experiment"
        | "release"
        | "decision_record"
        | "stakeholder"
        | "initiative"
        | "periodic_review";
      /**
       * Level
       * @enum {string}
       */
      level: "L0" | "L1" | "L2" | "L3";
    };
    /** Body_import_apply_bundles_import_apply_post */
    Body_import_apply_bundles_import_apply_post: {
      /** File */
      file: string;
      /**
       * Resolutions
       * @default {}
       */
      resolutions: string;
    };
    /** Body_import_validate_bundles_import_validate_post */
    Body_import_validate_bundles_import_validate_post: {
      /** File */
      file: string;
    };
    /**
     * ChatTask
     * @description チャットタスク1件分の情報。
     */
    ChatTask: {
      /** Id */
      id: string;
      /** Message */
      message: string;
      /** Product Id */
      product_id: string;
      /** Actor */
      actor: string;
      /** @default pending */
      status: components["schemas"]["ChatTaskStatus"];
      /** Result */
      result?: {
        [key: string]: unknown;
      } | null;
      /** Error */
      error?: string | null;
      /** Intent */
      intent?: string | null;
    };
    /**
     * ChatTaskRequest
     * @description `POST /chat/instructions`のリクエストボディ。
     */
    ChatTaskRequest: {
      /** Message */
      message: string;
      /** Product Id */
      product_id: string;
    };
    /**
     * ChatTaskStatus
     * @description チャットタスクの状態。
     * @enum {string}
     */
    ChatTaskStatus: "pending" | "running" | "done" | "failed";
    /**
     * ChatTaskTransitionRequest
     * @description `POST /chat/tasks/{id}/transition`のリクエストボディ。
     */
    ChatTaskTransitionRequest: {
      status: components["schemas"]["ChatTaskStatus"];
      /** Result */
      result?: {
        [key: string]: unknown;
      } | null;
      /** Error */
      error?: string | null;
      /** Intent */
      intent?: string | null;
    };
    /** CostSummaryResponse */
    CostSummaryResponse: {
      /** Period */
      period: string;
      /** Budget Monthly Jpy */
      budget_monthly_jpy: number;
      /** Total Spend Jpy */
      total_spend_jpy: number;
      /** Consumption Ratio */
      consumption_ratio: number;
      /** Budget Status */
      budget_status: string;
      /** By Model */
      by_model: components["schemas"]["AggregatedUsageResponseEntry"][];
      /** By Logical Name */
      by_logical_name: components["schemas"]["AggregatedUsageResponseEntry"][];
      /** By Day */
      by_day: components["schemas"]["AggregatedUsageResponseEntry"][];
    };
    /** CreateUserRequest */
    CreateUserRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
      /**
       * Role
       * @enum {string}
       */
      role: "admin" | "editor" | "viewer";
      /** Totp Secret */
      totp_secret?: string | null;
      /** Product Scopes */
      product_scopes?: string[] | null;
    };
    /** DecideRequest */
    DecideRequest: {
      /**
       * Decision
       * @enum {string}
       */
      decision: "approved" | "rejected";
      /** Approver */
      approver: string;
      /** Reason */
      reason: string;
    };
    /** EmergencyStopResponse */
    EmergencyStopResponse: {
      /** Emergency Stopped */
      emergency_stopped: boolean;
    };
    /** ExportRequest */
    ExportRequest: {
      /** Product Ids */
      product_ids?: string[] | null;
      /** Kinds */
      kinds?: string[] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
      /** Totp Code */
      totp_code?: string | null;
    };
    /** ProposalResponse */
    ProposalResponse: {
      /** Id */
      id: string;
      /** Target */
      target: string;
      /** Proposer */
      proposer: string;
      status: components["schemas"]["ProposalState"];
      /** Approver */
      approver?: string | null;
      /** Reason */
      reason?: string | null;
      /** Approval Entity Id */
      approval_entity_id?: string | null;
      /** Draft */
      draft?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * ProposalState
     * @description 承認プロポーザルの状態。
     * @enum {string}
     */
    ProposalState: "proposed" | "approved" | "rejected";
    /** ProposeRequest */
    ProposeRequest: {
      /** Target */
      target: string;
      /** Proposer */
      proposer: string;
      /** Draft */
      draft?: {
        [key: string]: unknown;
      } | null;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Access Token */
      access_token: string;
    };
    /** SetLevelRequest */
    SetLevelRequest: {
      /**
       * Level
       * @enum {string}
       */
      level: "L0" | "L1" | "L2" | "L3";
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** UpdateScopesRequest */
    UpdateScopesRequest: {
      /** Product Scopes */
      product_scopes: string[] | null;
    };
    /**
     * UsageRequest
     * @description `POST /costs/usage`のリクエストボディ。
     */
    UsageRequest: {
      /** Logical Name */
      logical_name: string;
      /** Model */
      model: string;
      /**
       * Prompt Tokens
       * @default 0
       */
      prompt_tokens: number;
      /**
       * Completion Tokens
       * @default 0
       */
      completion_tokens: number;
      /**
       * Latency Ms
       * @default 0
       */
      latency_ms: number;
      /**
       * Cost Jpy
       * @default 0
       */
      cost_jpy: number;
      /**
       * Actor
       * @default
       */
      actor: string;
      /** Detail */
      detail?: {
        [key: string]: unknown;
      };
    };
    /** UsageResponse */
    UsageResponse: {
      /**
       * Recorded
       * @default true
       */
      recorded: boolean;
    };
    /** UserResponse */
    UserResponse: {
      /** Id */
      id: string;
      /** Email */
      email: string;
      /**
       * Role
       * @enum {string}
       */
      role: "admin" | "editor" | "viewer";
      /** Product Scopes */
      product_scopes?: string[] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_user_admin_users_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_scopes_admin_users__user_id__scopes_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateScopesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_records_audit_records_get: {
    parameters: {
      query?: {
        actor?: string | null;
        action?: string | null;
        kind?: string | null;
        date_from?: string | null;
        date_to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditRecord"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_proposals_approvals_get: {
    parameters: {
      query?: {
        status?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  propose_approvals_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProposeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  decide_approvals__proposal_id__decide_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        proposal_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecideRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_autonomy_levels_autonomy_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AutonomyConfig"][];
        };
      };
    };
  };
  set_autonomy_level_autonomy__product_id___business_function__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
        business_function: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetLevelRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AutonomyConfig"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_emergency_stop_status_autonomy_emergency_stop_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmergencyStopResponse"];
        };
      };
    };
  };
  trigger_emergency_stop_autonomy_emergency_stop_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmergencyStopResponse"];
        };
      };
    };
  };
  release_emergency_stop_autonomy_emergency_stop_release_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmergencyStopResponse"];
        };
      };
    };
  };
  export_entities_bundles_export_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_validate_bundles_import_validate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_validate_bundles_import_validate_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_apply_bundles_import_apply_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_apply_bundles_import_apply_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_instructions_chat_instructions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatTaskRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatTask"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tasks_chat_tasks_get: {
    parameters: {
      query?: {
        status?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatTask"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_task_chat_tasks__task_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatTask"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  transition_task_chat_tasks__task_id__transition_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatTaskTransitionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatTask"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  record_usage_costs_usage_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UsageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_cost_summary_costs_summary_get: {
    parameters: {
      query?: {
        period?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CostSummaryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  execute_decision_pmdf_decision__id__execute_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  confirm_roadmap_item_roadmap__id__confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  release_go_no_go_release__id__go_no_go_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  send_stakeholder_message_stakeholder__id__send_message_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_entities_pmdf__kind__get: {
    parameters: {
      query?: {
        product?: string | null;
      };
      header?: never;
      path: {
        kind: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_entity_pmdf__kind__post: {
    parameters: {
      query?: never;
      header?: {
        "X-Agent-Actor"?: string | null;
      };
      path: {
        kind: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_entity_history_pmdf__kind___id__history_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kind: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_entity_pmdf__kind___id__get: {
    parameters: {
      query?: {
        ref?: string | null;
      };
      header?: never;
      path: {
        kind: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_entity_pmdf__kind___id__put: {
    parameters: {
      query?: never;
      header?: {
        "X-Agent-Actor"?: string | null;
      };
      path: {
        kind: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_entity_pmdf__kind___id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        kind: string;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
